// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleDesk.Infrastructure.Contexts;

#nullable disable

namespace PeopleDesk.Infrastructure.Migrations
{
    [DbContext(typeof(PeopleDeskDbContext))]
    partial class PeopleDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeopleDesk.Domain.Entities.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtualizadoEm");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Descricao");

                    b.Property<DateTime?>("FechadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechadoEm");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("IniciadoEm");

                    b.Property<string>("ObservacaoFechamento")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ObservacaoFechamento");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("Prioridade");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Titulo");

                    b.Property<Guid>("UsuarioCriadorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioCriadorId");

                    b.Property<Guid?>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioResponsavelId");

                    b.HasKey("Id");

                    b.HasIndex("Prioridade")
                        .HasDatabaseName("IX_Chamados_Prioridade");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Chamados_Status");

                    b.HasIndex("UsuarioCriadorId")
                        .HasDatabaseName("IX_Chamados_UsuarioCriadorId");

                    b.HasIndex("UsuarioResponsavelId")
                        .HasDatabaseName("IX_Chamados_UsuarioResponsavelId");

                    b.ToTable("Chamados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
